### PR TITLE
fix(command-compile): rebase before compiling and fetch origin

### PR DESCRIPTION
**Pull request by skjnldsv**
```sh
/compile
/compile amend /
/compile fixup /
/compile rebase-amend /
/compile rebase-fixup /
```

### Note

PS: it will NOT resolve conflicts for you (could be amazing to drop any conflicts on `/js` or `/dist`)

## References

1. https://github.com/nextcloud/privacy/pull/1022#issuecomment-1921072459
2. https://github.com/nextcloud/privacy/actions/runs/7740264658?pr=1022

### CODE REVIEW

**Comment by nickvergessen** [comment]
`/compile rebase /` also works?

**Comment by skjnldsv** [comment]
> `/compile rebase /` also works?

should be yes

> PS: it will NOT resolve conflicts for you (could be amazing to drop any conflicts on `/js` or `/dist`)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/privacy/pull/1026#issuecomment-1922009503

:popcorn:

**Comment by skjnldsv** [comment]
> should be yes

no, because we need a force push then

**Comment by skjnldsv** [comment]
Here you go @nickvergessen !

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
