### PR TITLE
feat: add classmap-authoritative to appstore-build-publish

### PR DESCRIPTION
**Pull request by skjnldsv**
https://github.com/nextcloud/spreed/pull/9629#discussion_r1206605890
https://getcomposer.org/doc/articles/autoloader-optimization.md

# Optimization Level 2/A: Authoritative class maps
## How to run it?
There are a few options to enable this:

- Set "classmap-authoritative": true inside the config key of composer.json
- Call install or update with -a / --classmap-authoritative
- Call dump-autoload with -a / --classmap-authoritative

## What does it do?
Enabling this automatically enables Level 1 class map optimizations.

This option says that if something is not found in the classmap, then it does not exist and the autoloader should not attempt to look on the filesystem according to PSR-4 rules.

## Trade-offs
This option makes the autoloader always return very quickly. On the flipside it also means that in case a class is generated at runtime for some reason, it will not be allowed to be autoloaded. If your project or any of your dependencies does that then you might experience "class not found" issues in production. Enable this with care.

Note: This cannot be combined with Level 2/B optimizations. You have to choose one as they address the same issue in different ways.

### CODE REVIEW

**Comment by skjnldsv** [comment]
> * Set "classmap-authoritative": true inside the config key of composer.json

Seeing this, we can also go for that option and let devs handle this on a case-by-case basis

**Comment by ChristophWurst** [comment]
Authoritative autoloaders lead to https://github.com/nextcloud/calendar/issues/5191 for app store apps

**Comment by skjnldsv** [comment]
> Authoritative autoloaders lead to [nextcloud/calendar#5191](https://github.com/nextcloud/calendar/issues/5191) for app store apps

Talk is using those :shrug: 
I'm just following the track from https://github.com/nextcloud/spreed/pull/9629#discussion_r1206605890

I have zero knowledge on this :/

**Comment by nickvergessen** [comment]
> I have zero knowledge on this :/

Same here, just approved the PR coming from christoph back then :P

**Comment by skjnldsv** [comment]
You're our lord and saviour @ChristophWurst :grin: 
What do we do then :see_no_evil:

**Comment by skjnldsv** [comment]
> > * Set "classmap-authoritative": true inside the config key of composer.json
> 
> Seeing this, we can also go for that option and let devs handle this on a case-by-case basis

Maybe this is the way ?
Not touch the workflows but the composer configs ?

**Pull request closed without merging**
