### PR TITLE
feat: cache git repository for faster checkout

### PR DESCRIPTION
**Pull request by skjnldsv**
On server, this reduce the workflow time by half! :speedboat: :rocket: 
Do you see any other location this might be useful?

- No cache: https://github.com/skjnldsv/server/actions/runs/5364983983/jobs/9733513243
  image
- Cache: https://github.com/skjnldsv/server/actions/runs/5365018048/jobs/9733568097
  image

### CODE REVIEW

**Review by szaimen — APPROVED** [review]
Wow nice! I cannot tell if this causes any side-effects but it is worth it to at least try it out for the time advantage! :)

And btw, wouldnt this make sense for any workflow that uses the checkout step? Or would this lead to complications?

**Comment by skjnldsv** [comment]
> And btw, wouldnt this make sense for any workflow that uses the checkout step? Or would this lead to complications?

I thought about it, and I could not see any downside to it.
The `action/checkout` seems to be smart enough to fetch any reference if the repo already exists in the fiulesystem.
I think we can try and extend this globally. If this fails somewhere, we can always revert.

In any case, the only issue I can think of is the max cache limit, which is 10GB per repo.
But worst case scenario, the old cache will be removed and the workflow will proceed as usual with the default old performances.

**Comment by szaimen** [comment]
> The `action/checkout` seems to be smart enough to fetch any reference if the repo already exists in the fiulesystem. I think we can try and extend this globally. If this fails somewhere, we can always revert.

Sounds good!

> In any case, the only issue I can think of is the max cache limit, which is 10GB per repo. But worst case scenario, the old cache will be removed and the workflow will proceed as usual with the default old performances.

All right!

**Comment by skjnldsv** [comment]
One thing that could cause issues, I just realized, is the `fetch-depth`.
If we start caching incomplete repos state, this might lead to undesired outcome.
We should maybe only have the caching step if `fetch-depth: 0` is set :thinking:

**Comment by skjnldsv** [comment]
Actually, this is  a good point, do we need `fetch-depth: 0` to compile?
I'm not sure :thinking: 

Checking out the last commit should be enough to amend anyway :thinking: 
Maybe this is entirely unecessary :see_no_evil:

**Comment by skjnldsv** [comment]
Push to only include the compile workflow. We can merge

**Review by susnux — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Pull request merged**
