### PR TITLE
Add automated dependabot approve and merge

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Comment by PVince81** [comment]
I'm not a fan, especially after that time where an automatic merge of a patch update of babel broke Talk with IE, ref: https://github.com/nextcloud/spreed/issues/4818. Now the benefit of automerge might still outweight the potential low risk of such breakage ?

**Comment by skjnldsv** [comment]
Well, for one that fails successfully, we have 100 that works and are safe to be auto-merged.
I think so far it helped us reduce a lot of our global dependabot process.
So far this has been enabled in almost all repos and for the last 18 months only a few issues were caught and reverted. :thinking:

**Comment by skjnldsv** [comment]
in any case @PVince81 talk is not using this, so you'r eon the safe side. This one will only update repos that already uses it :)

**Review by PVince81 — APPROVED** [review]
:+1: fine by me

we should anyway smoke test with browsers before releasing

**Pull request merged**
