### PR TITLE
feat(info.xml lint): Run info.xml lint only for relevant PRs

### PR DESCRIPTION
**Pull request by ChristophWurst**
1) Don't lint arbitrary pushes
2) Don't lint if info.xml hadn't been touched

### CODE REVIEW

**Comment by ChristophWurst** [comment]
This will probably bite for required checks https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks :smiling_face_with_tear:

**Comment by AlvaroBrey** [comment]
> This will probably bite for required checks https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks smiling_face_with_tear

> You can fix this by creating a generic workflow, with the same name, that will return true in any case

GitHub CI workarounds never cease to amaze, eh?

**Comment by ChristophWurst** [comment]
One day we will have 4k LOC of workflow yaml for 200 LOC source code

**Comment by ChristophWurst** [comment]
With https://github.com/nextcloud/.github/pull/104 rejected both approaches go into the bin apparently -> closing

**Pull request closed without merging**
