### PR TITLE
Fix logic to run tests on pushes

### PR DESCRIPTION
**Pull request by nickvergessen**
* Before Talk merges failed to execute the jobs: https://github.com/nextcloud/spreed/actions/runs/6530409072
* Fixed Talk: https://github.com/nextcloud/spreed/actions/runs/6531152220

### CODE REVIEW

**Comment by kesselb** [comment]
Well spotted :+1: 

paths-filter needs a git checkout for push because the api, to fetch changed files, only works for pull requests. 

For lint and node we could merge the changes step into the build step because we usually don't need a matrix and run the path filter after the git checkout.

For phpunit* we need a git checkout before running the path filter or continue on error. 

Alternative: We don't run the workflow for pushes anymore.

**Comment by nickvergessen** [comment]
> Alternative: We don't run the workflow for pushes anymore.

We want the results of pushes, so it's easier to find the first failing state etc, e.g. when 2 parallel PRs cause issues.

**Comment by kesselb** [comment]
```
- name: Checkout
  if: ${{ github.event_name == 'push' }}
  uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
```

Instead of continue_on_error maybe?

**Review by skjnldsv — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Instead of continue_on_error maybe?

We could, but that would mean we don't check the result on each PR anymore, but only such that changed something. Also would mean translation updates don't run CI anymore, so instead I favor to always run the CI checks on such pushes.

**Review by kesselb — APPROVED** [review]
:+1:

**Pull request merged**
