### PR TITLE
Restore loop and fix pagination

### PR DESCRIPTION
**Pull request by skjnldsv**
- https://github.com/nextcloud/.github/actions/runs/3255258097
- https://github.com/nextcloud/.github/actions/runs/3255278696
- https://github.com/nextcloud/.github/actions/runs/3255279620
- https://github.com/nextcloud/.github/actions/runs/3255280052
- https://github.com/nextcloud/.github/actions/runs/3255284698

### CODE REVIEW

**Comment by nickvergessen** [comment]
But the code search didn't work I think?

**Comment by nickvergessen** [comment]
But e.g. https://github.com/nextcloud/announcementcenter/pulls?q=is%3Apr+is%3Aclosed didn't get the node.yml updated?

**Comment by skjnldsv** [comment]
> But e.g. [nextcloud/announcementcenter/pulls (is:closed)](https://github.com/nextcloud/announcementcenter/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc) didn't get the node.yml updated?

I didn't dispatched node.yml lol
CI got completely saturated already with the few I made

**Comment by nickvergessen** [comment]
Please don't execute. I will replace/patch all files next week with the php 7.4 drop 🙈

**Comment by skjnldsv** [comment]
Ah, I read execute as "merge"

We can still merge but I'll leave it to you to dispatch the changes next week then, sure :)

**Pull request closed without merging**
