### PR TITLE
feat(CI): Add PHPUnit testing for PHP 8.2

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref https://github.com/nextcloud/server/pull/36375

### CODE REVIEW

**Comment by come-nc** [comment]
See also https://github.com/nextcloud/server/pull/32463

**Comment by come-nc** [comment]
> Should we also add this?
> 
> [nextcloud/server@f0e88ce#diff-dafcb7f3e7c61408e9b52befb8a557ba90eb708d6f55fcc265447776152678cdR39](https://github.com/nextcloud/server/commit/f0e88ce22e7c2c4ee7ad356baa0bd60ce0bafebd#diff-dafcb7f3e7c61408e9b52befb8a557ba90eb708d6f55fcc265447776152678cdR39)

Yes please.

**Comment by come-nc** [comment]
> Should we also add this?
> 
> [nextcloud/server@f0e88ce#diff-dafcb7f3e7c61408e9b52befb8a557ba90eb708d6f55fcc265447776152678cdR39](https://github.com/nextcloud/server/commit/f0e88ce22e7c2c4ee7ad356baa0bd60ce0bafebd#diff-dafcb7f3e7c61408e9b52befb8a557ba90eb708d6f55fcc265447776152678cdR39)

Yes please.

**Comment by blizzz** [comment]
What's the thing  with the ini file?

**Comment by nickvergessen** [comment]
> What's the thing with the ini file?

The ini file is from PHP upstream as far as I can tell

**Review by blizzz — APPROVED** [review]

**Pull request merged**
