### PR TITLE
Run PHPUnit workflows on main branch

### PR DESCRIPTION
**Pull request by Pytal**
See title 👆

### CODE REVIEW

**Comment by Pytal** [comment]
Could a repo admin give the https://github.com/orgs/nextcloud/teams/server team access for review requests?

**Review by nickvergessen — APPROVED** [review]

**Comment by nickvergessen** [comment]
> Could a repo admin give the https://github.com/orgs/nextcloud/teams/server team access for review requests?

Should all be normal, you just can not request review from the team as the repo is not assigned to the team

**Comment by nickvergessen** [comment]
@skjnldsv how did the automatic updating work?

**Comment by skjnldsv** [comment]
> @skjnldsv how did the automatic updating work?

https://github.com/nextcloud/.github#auto-update-repositories

**Pull request merged**
