### PR TITLE
fix permissions for the rebase workflow

### PR DESCRIPTION
**Pull request by szaimen**
Fix https://github.com/nextcloud/.github/issues/55

Signed-off-by: szaimen <szaimen@e.mail.de>

### CODE REVIEW

**Review by blizzz — APPROVED** [review]

**Comment by szaimen** [comment]
@skjnldsv can we please update the command-rebase templates in the org? I don't have enough permissions here to do this...

**Comment by blizzz** [comment]
> @skjnldsv can we please update the command-rebase templates in the org? I don't have enough permissions here to do this...

i triggered it, i think :popcorn:

**Comment by szaimen** [comment]
thanks but it doesnt look like it worked... server did not get a PR...

**Comment by blizzz** [comment]
> thanks but it doesnt look like it worked... server did not get a PR...

:sos: @skjnldsv (and how to do it correctly?)

**Comment by blizzz** [comment]
worked only for three repos:

Screenshot_20220426_161032

**Comment by blizzz** [comment]
Maybe it's rate limiting? What do you get for

```bash
REPOS=$(curl -H "Accept: application/vnd.github.v3+json" "https://api.github.com/search/code?q=org%3Anextcloud%20path%3A.github%2Fworkflows%20filename%3Acommand-rebase.yml&per_page=100" | jq -c '.items | map(.repository.name) | unique')
echo $REPOS
```

I get different results regularly

**Comment by szaimen** [comment]
So whenever incomplete_results is true we need to perform an additional request?

**Comment by blizzz** [comment]
> So whenever incomplete_results is true we need to perform an additional request?

Well it says it is completed when there were only 2 results. That cannot be true. It's unreliable.

**Comment by szaimen** [comment]
> Well it says it is completed when there were only 2 results. That cannot be true. It's unreliable.

that is bad

**Comment by skjnldsv** [comment]
> worked only for three repos:

Github search is :hankey: 
Trigger it again and get different  repositories results...

**Comment by skjnldsv** [comment]
> > So whenever incomplete_results is true we need to perform an additional request?
> 
> Well it says it is completed when there were only 2 results. That cannot be true. It's unreliable.

Yep, it used to be good, but broke a few months ago. Now I always have to trigger it multiple times :face_exhaling:

**Pull request merged**
